site_name: FastSQLA
site_url: https://mydomain.org/FastSQLA
repo_name: hadrien/FastSQLA
repo_url: https://github.com/hadrien/fastsqla
edit_uri: edit/main/docs/

nav:
- Get Started:
  - Welcome to FastSQLA: index.md
- Usage:
  - Setup: setup.md
  - Object-relational mapping: orm.md
  - SQLAlchemy Session: session.md
  - Pagination: pagination.md
- Changelog: changelog.md

theme:
  favicon: images/favicon.png
  icon:
    logo: material/database
  name: material
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference

plugins:
  - autorefs
  - glightbox
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          import:
          - https://docs.python.org/3/objects.inv
          - https://docs.sqlalchemy.org/en/20/objects.inv
          - https://fastapi.tiangolo.com/objects.inv
  - search
  - llmstxt:
      markdown_description: |
        Async SQLAlchemy 2.0+ extension for FastAPI with SQLModel support, built-in pagination & more.
      full_output: llms-full.txt
      sections:
        Sections:
        - index.md
        - setup.md
        - session.md
        - orm.md
        - pagination.md

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - toc:
      permalink: true
watch:
  - docs
  - src
