name: Setup tox-uv
description: Setup tox-uv tool so tox uses uv to install dependencies
runs:
  using: composite
  steps:
    - name: ⚡️ setup uv
      uses: .github/uv
      run: uv tool install tox --with tox-uv

