name: Dependabot auto-merge

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    if: >-
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      github.repository == 'hadrien/FastSQLA'
    runs-on: ubuntu-latest
    steps:
      - name: Approve pull request
        run: gh pr review --approve "$PR_URL"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
      - name: Enable auto-merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
