name: Publish on PyPI

on:
  push:
    branches:
      - main

jobs:

  Publish:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write
    steps:
    - name: 📥 checkout
      uses: actions/checkout@v4
    - name: 🔧 setup uv
      uses: ./.github/uv
    - name: 📜 semantic release version
      run: |
        uv run semantic-release --strict version
        RET_CODE=$?
        if [ $RET_CODE -ne 0 ]; then
          echo "Nothing to publish"
          exit 0
        fi
      continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: 🛠️ build
      run: uv build
    - name: 📰 publish on pypi
      run: uv run twine upload dist/*
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
