name: Release & Publish

on:
  push:
    branches:
      - main

jobs:

  Release-And-Publish:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      contents: write
      id-token: write
    steps:
    - name: 📥 checkout
      uses: actions/checkout@v7
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
    - name: 🔧 setup uv
      uses: ./.github/uv
    - name: 📜 semantic release version & publish on PyPI
      run: |
        next_version=$(uv run semantic-release version --print)
        last_released_version=$(uv run semantic-release version --print-last-released)
        if [[ "$next_version" == "$last_released_version" ]]; then
          echo "🙅🏽 Nothing to publish"
        else
          uv run semantic-release --strict version
          echo "🙆🏽 Publishing on PyPI"
          uv build
          uv run twine upload dist/*
        fi
      env:
        GH_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
