name: uv

on:
    workflow_call:

jobs:

  Setup:
    runs-on: ubuntu-latest
    steps:
    - name: 📥 checkout
      uses: actions/checkout@v4
    - name: ⚡️ setup uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"
        enable-cache: true
        cache-suffix: 2024-09-08 09:10
        cache-dependency-glob: "uv.lock"
